apiVersion: v1
kind: Service
metadata:
  name: donation-system-service
spec:
  type: LoadBalancer
  selector:
    app: donation-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
